name: Build Image
on:
  push:
    branches:
      - master
    paths-ignore:
      - ".dockerignore"
      - ".gitignore"
      - "README.rst"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/jacky9813/sample_server:${{ github.sha }}
      - name: Run Trivy
        uses: aquasecurity/trivy-action
        with:
          image-ref: ghcr.io/jacky9813/sample_server:${{ github.sha }}
          format: sarif
          output: trivy-result.sarif
      - name: Upload trivy scan result to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-result.sarif
